apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GIT_SYNC_USERNAME: bWFyaXVzc3MyMQ==
  GITSYNC_USERNAME: bWFyaXVzc3MyMQ==
  GIT_SYNC_PASSWORD: MzI1MTEzNzVhPQ==
  GITSYNC_PASSWORD: MzI1MTEzNzVhPQ==
