apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/mariusss21/test-argocd-airflow.git'
    path: /
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: 'test-argocd-airflow'
    namespace: airflow
    server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true